### ISSUE TITLE
Add possibility to ingest locally served models APIs

### ISSUE THREAD

**Issue by ELigoP** [joorjeh/toolla#1]
- llama.cpp server
- koboldcpp
- LMStudio

and plenty of other tools expose API endpoint with OpenAI specification. Would be nice to provide custom endpoint together with model name.

**Comment by joorjeh** [comment]
Yes! I'm working on local support now that will take any OpenAI compatible endpoint.  

OpenAi/Anthropic have some in-house process for determining tool use on their end and return the appropiate values in their responses.  I'm not sure how they do it, but I hacked together a solution for open models with a custom system prompt and naive checks for JSON in the response.  Definitely a work in progress and am super open to suggestions.

**Comment by joorjeh** [comment]
@ELigoP feature added with 0.2.0 release, closing
